apiVersion: v1
kind: Template
metadata:
  name: gradle-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: demo-gradle-jenkins
    name: demo-gradle-jenkins
  spec:
    successfulBuildHistoryLimit: 2
    failedBuildHistoryLimit: 2
    source:
      git:
        uri: https://github.com/avrylkov/jenkins-slave-gradle.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile